/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Project_01;

/**
 *
 * @author Pasindu Purna
 */
public class HangmanProjectFrame extends javax.swing.JFrame {
    private static Object frame;

    /**
     * Creates new form HangmanProjectFrame
     */
    public HangmanProjectFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblOne = new javax.swing.JLabel();
        lblTwo = new javax.swing.JLabel();
        lblThree = new javax.swing.JLabel();
        lblFour = new javax.swing.JLabel();
        lblFive = new javax.swing.JLabel();
        txtInput = new javax.swing.JTextField();
        lblCount = new javax.swing.JLabel();
        btnTry = new javax.swing.JButton();
        btnHangman = new javax.swing.JButton();
        txtMessage = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Guess the Word Game");

        lblOne.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        lblOne.setText("X");

        lblTwo.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        lblTwo.setText("X");

        lblThree.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        lblThree.setText("X");

        lblFour.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        lblFour.setText("X");

        lblFive.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        lblFive.setText("X");

        txtInput.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N

        lblCount.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblCount.setText("0");

        btnTry.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnTry.setText("Try Letter");
        btnTry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTryActionPerformed(evt);
            }
        });

        btnHangman.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project_01/HangMan-00.jpg"))); // NOI18N
        btnHangman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHangmanActionPerformed(evt);
            }
        });

        txtMessage.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtMessage.setText("Message");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblOne)
                                .addGap(18, 18, 18)
                                .addComponent(lblTwo)
                                .addGap(18, 18, 18)
                                .addComponent(lblThree)
                                .addGap(18, 18, 18)
                                .addComponent(lblFour)
                                .addGap(18, 18, 18)
                                .addComponent(lblFive))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblCount, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtInput, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnTry, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(35, 35, 35)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtMessage, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(btnHangman, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnHangman, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblOne)
                            .addComponent(lblTwo)
                            .addComponent(lblThree)
                            .addComponent(lblFour)
                            .addComponent(lblFive))
                        .addGap(43, 43, 43)
                        .addComponent(txtInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(lblCount)
                        .addGap(31, 31, 31)
                        .addComponent(btnTry)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                        .addComponent(txtMessage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    String[] words = {"hello", "bulbs", "world", "apple", "phone", "women"};
    int random = (int) (Math.random() * 6);
    public int correctCount = 0;
    public int wrongCount = 0;
    public String guessWords = words[random];

    private void btnTryActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
        char[] value = new char[5];//creating a char array 
        for (int i = 0; i < guessWords.length(); i++) {
            value[i] = guessWords.charAt(i);
        }
        try{
            char input = txtInput.getText().toLowerCase().charAt(0);//Converting the input to lowercase
            int count = 0;
            //Using a for loop  linear search of the words to guess
            for (int i = 0; i < guessWords.length(); i++) {
                if (input == value[i]) {
                    //switch case
                    switch (i) {
                        case 0:
                            lblOne.setText(input + "");
                            break;
                        case 1:
                            lblTwo.setText(input + "");
                            break;
                        case 2:
                            lblThree.setText(input + "");
                            break;
                        case 3:
                            lblFour.setText(input + "");
                            break;
                        case 4:
                            lblFive.setText(input + "");
                            break;
                        }
                    correctCount++;//Incrementing
                } else {
                    count++;//Incrementing
                }
                if (count == guessWords.length()) {
                    count = 0;
                    wrongCount++;//Incrementing
                    lblCount.setText(wrongCount + "");
                    txtMessage.setText("Wrong Guess, Input a New Letter");
                }else{
                    txtMessage.setText("Guess is correct, Input a New Letter");
                }
                if (correctCount == guessWords.length()) {
                    txtMessage.setText("Congratulations you have won.  Game over");
                }
            }
            txtInput.setText("");
        } catch (Exception e) {
            txtMessage.setText("Input a Letter");
        }
        
        //Set ImageIcon
        if (wrongCount == 1) {
            btnHangman.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project_01/HangMan-01.jpg")));
        } else if (wrongCount == 2) {
            btnHangman.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project_01/HangMan-02.jpg")));
        } else if (wrongCount == 3) {
            btnHangman.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project_01/HangMan-03.jpg")));
        } else if (wrongCount == 4) {
            btnHangman.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project_01/HangMan-04.jpg")));
        } else if (wrongCount == 5) {
            btnHangman.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project_01/HangMan-05.jpg")));
        } else if (wrongCount == 6) {
            txtMessage.setText("You did not win.  Game over.");
            btnHangman.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project_01/HangMan-06.jpg")));
        }  
   }                                      

    private void btnHangmanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHangmanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHangmanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HangmanProjectFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HangmanProjectFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HangmanProjectFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HangmanProjectFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HangmanProjectFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHangman;
    private javax.swing.JButton btnTry;
    private javax.swing.JLabel lblCount;
    private javax.swing.JLabel lblFive;
    private javax.swing.JLabel lblFour;
    private javax.swing.JLabel lblOne;
    private javax.swing.JLabel lblThree;
    private javax.swing.JLabel lblTwo;
    private javax.swing.JTextField txtInput;
    private javax.swing.JTextField txtMessage;
    // End of variables declaration//GEN-END:variables
}
